### ISSUE TITLE
Tree doe not support complex type inside an array 

### ISSUE THREAD

**Issue by mastermind1981** [berkesa/datatree#1]
Hi,

Thanks for your the datatree framework I've found it very useful.
I got a problem when having path where  containing an array of a complex type or a collection/array of a complex type.
the showcase of the problem (collection of a collection of a complex type)
`tree.put("kycScoreResponse._return.resultDatas[0].actions[0].type", "value");`
returns an NPE.
Also, If use  a collection of a complex type like below I got an NPE
`tree.put("kycScoreResponse._return.resultDatas[0].actions.type", "value");`
If I have a collection/array of simple type it works fine like in the example blow
`tree.put("kycScoreResponse._return.resultDatas[0].actions", "value");`

Is there any workaround?

**Comment by berkesa** [comment]
Hi @mastermind1981!

What do you mean by complex type? Java Beans with getter and setter methods? If so, it is not possible to dynamically modify its content (can only be used for generating JSONs with Jackson API). The Tree API designed for working with Collections. 

Tree API doesn't use reflection for speed and simplicity, only works with collection classes (**Map, List, Array**) and generic data types. These generic types are: **numbers (int, float, short, double, BigDecimal, BigInteger, byte, long), String, Date, InetAddress, UUID, Boolean and byte array**.

If you want to put Java Beans into a Tree, convert them into a simple, hierarchical collection-based structure. For this purpose (to convert POJO to Map), use the ObjectMapper class. The Map created with the ObjectMapper can be wrapped with a Tree object:

```java
ObjectMapper objectMapper = new com.fasterxml.jackson.databind.ObjectMapper();
Map<String, Object> map = objectMapper.convertValue(pojo, Map.class);
Tree tree = new Tree(map);
tree.put("kycScoreResponse._return.resultDatas[0].actions.type", "value");
```

**Comment by mastermind1981** [comment]
@berkesa thanks ... In fact, I was abusing the API a little ... my goal was to generate a properties file by constructing a Tree representing a class hierarchy with default values for the fields and storing the constructed Tree as Properties ... it worked except in the scenario  described in my message

**Comment by berkesa** [comment]
Ok, I understand. With the method above you can save POJO objects in the following formats:

- JSON (human-readable)
- YAML (human-readable)
- TOML (human-readable)
- SMILE (binary)
- BSON (binary)
- CBOR (binary)
