### ISSUE TITLE
Tree.getObject("path", null) will return default null if object is found

### ISSUE THREAD

**Issue by dealhubsharon** [berkesa/datatree#2]
Tree.getObject("path", null) will return null default value if path is found.
this is because of the if statement at #2968
if (child != null && defaultValue != null) {

**Comment by berkesa** [comment]
Thanks!
I fixed it. I'll upload a newer version in a few hours.

**Comment by berkesa** [comment]
Upgrade to datatree-core V1.0.14:

```xml
<dependency>
    <groupId>com.github.berkesa</groupId>
    <artifactId>datatree-core</artifactId>
    <version>1.0.14</version>
</dependency>
```
10 to 15 minutes for this version to appear in the Maven repository ...
